### PR TITLE
feat: ignore extension

### LINKED ISSUE #57: Ignore extension when comparing files
I have this scenario:

I am doing code migrations, and usually I would like to compare old code with new code.
If for example I am migrating from Visual Basic to C# files are .vb and .cs is there a way to ignore the extension 
I would like to have the side by side

### PR DESCRIPTION
**Pull request by moshfeu**
resolve #57 

[~compare-folders-0.19.0.vsix.zip~](https://github.com/moshfeu/vscode-compare-folders/files/5541183/compare-folders-0.19.0.vsix.zip)

[compare-folders-0.19.2.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/5612797/compare-folders-0.19.2.vsix.zip)

### CODE REVIEW

**Comment by moshfeu** [comment]
@gliviu what do you think?
https://github.com/moshfeu/vscode-compare-folders/pull/58/commits/ee3b2a9a091a013f27b97e0f9d4e6a1417be4441#diff-2a8e25e98543d9d6718152d94c3ae02db3439ba2358285b236979ad6465564d1R12-R27

**Comment by gliviu** [comment]
Looks good

**Comment by moshfeu** [comment]
Thanks @gliviu it was pleasure developing with you :)

**Comment by gliviu** [comment]
same on my side :)

**Pull request merged**
