### PR TITLE
feat: respect .gitignore

### LINKED ISSUE #96: [feature request] Add an option to auto exclude files from .gitignore
I compare two huge folders, which appear to be git repository.
There is a lot of temporary binary files and I'm using "compareFolders.excludeFilter" to remove them from comparison.
I feel like rewriting my gitignore in a different format.

### PR DESCRIPTION
**Pull request by moshfeu**
close #96

### CODE REVIEW

**Comment by placasse** [comment]
Glad that you like the idea.
Thanks for this fast patch.

Some points:
* Folder suffixed with / are not correctly interpreted (https://git-scm.com/docs/gitignore#:~:text=The%20pattern%20foo/,-will%20match%20a)
* .gitignore files from sub-folders should also be read
* .git folder should be ignored when "compareFolders.respectGitIgnore": true
* pattern negated by ! should not be ignored (add to includeFilter ?) (https://git-scm.com/docs/gitignore#:~:text=prefix%20%22!%22%20which%20negates)

**Comment by moshfeu** [comment]
Thank you for the valuable feedback!

I'll take care of the points you mentioned.
About the  .gitignore in subfolders, it's more tricky. I'd prefer to have another issue and see how much demand this request has and meantime to focus on other feature requests. Sounds fair?

**Comment by moshfeu** [comment]
Bottom line, this PR adds the core feature and handles patterns start with `!`
A follow up PR will handle `.git` folder.
Need to check about the rest two.

**Comment by moshfeu** [comment]
Almost a year later 😅 I finalized the feature but ".gitignore files from sub-folders should also be read" which, as I mentioned, more complicated.. not rocket science, but still.

@placasse would you mind to give it a try?

[compare-folders-0.23.0.vsix.zip](https://github.com/moshfeu/vscode-compare-folders/files/12207767/compare-folders-0.23.0.vsix.zip)

**Comment by atplacasse** [comment]
Sure!
Here is a test case not yet working. Given this .gitgnore:
```
a*
!a1.txt
```
then file a1.txt should not be ignored.

**Comment by moshfeu** [comment]
Thanks for the quick feedback!
@gliviu any advice here? Should `includeFilter: a1.txt` take over `excludeFilter: a*`?

@atplacasse If this is the only issue, I'll merge the PR and kindly ask you to create a new issue so people could enjoy the feature until we figure it out.

**Comment by gliviu** [comment]
Sure. I will take a look in the next few days.

**Comment by moshfeu** [comment]
> Sure. I will take a look in the next few days.

Thanks 🙏

**Comment by atplacasse** [comment]
@moshfeu Ok then I created https://github.com/moshfeu/vscode-compare-folders/issues/126

**Comment by moshfeu** [comment]
> @moshfeu Ok then I created https://github.com/moshfeu/vscode-compare-folders/issues/126
> 

Thanks

**Pull request merged**
