### PR TITLE
Compare file from folder

### LINKED ISSUE #18: List compared folders in settings
I always compared same folders, it could be useful to set a list of folders in settings so we can pickup when needed.

### PR DESCRIPTION
**Pull request by llgcode**
Fixes #18 and #19

### CODE REVIEW

**Comment by moshfeu** [comment]
Thank you for the your work!
I have to be honest, it feels not that intuitive for me. I wasn't sure, at the beginning what should I do. Because if I right click on a **file** but I can't choose a **file** in the dialog (because I need to select a **folder** that contains a file with the same name for comparing).

I like the idea of favorite or recent folders though. It can be saved on a [storage](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage).

WDYT?

**Comment by llgcode** [comment]
We use at work, a versioning software where each big revision are in separate folders. We always compare files against each other from that projects. 
I understand your point that is not so understabke but for my day to day work it is a feature so useful, that I can't do without it.
A compromise could be to compare against the current folder that is actually compared.
Recent folders is a good idea.
Thanks for your comment.

**Comment by llgcode** [comment]
I think we could improve the readability of this feature by:
- renaming the menu to something like: Compare with the Same File from "Compared Folder"
- if a current folder is actually compared in Compare Folders View so use this folder to search the corresponding file. If no current folder, open a list of recent compared folders + a special item "Choose a Folder..." that will open a File Dialog.
I may implement it next week.
What do you think ?

**Comment by moshfeu** [comment]
Sorry I still find it a bit confusing and not common case.
But, more features is great so I would suggest to allow the user to enable this feature in the settings by set the contributor's [when clause](https://code.visualstudio.com/docs/getstarted/keybindings#_contexts) to `config.compareFolders.{config_name}` (can be found under `Configuration settings contexts`)

**Comment by moshfeu** [comment]
I will close it for now. If it will be relevant in the future, please create a new one.

**Pull request closed without merging**
